#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`
cd $WRDIR

. ./init_params

for CONTAINER in $(docker ps -a   |grep "$DOCK_IMAGE" |awk '{print $1}')
do
docker rm $CONTAINER
done
cd $SAVEDIR