#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`
DT_LOCATION=$WRDIR

. $WRDIR/init_params

if [ "$USER" = "" ]; then echo i need Username;exit; fi



docker run -d \
-v $DT_LOCATION/etc/dt-auto-backup.conf:/dt-auto-backup/etc/dt-auto-backup.conf \
-v $BACKUPDIR:/dt-auto-backup/backup \
-v $DT_LOCATION/run:/dt-auto-backup/run \
-v $DT_LOCATION/log:/dt-auto-backup/log \
-v $DT_LOCATION/reports:/dt-auto-backup/reports \
-v /etc/localtime:/etc/localtime \
$PRM_SGN \
--cap-add SYS_ADMIN \
--cap-add DAC_READ_SEARCH \
--privileged \
--name $1-$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM \
--rm \
$DOCK_IMAGE /dt-auto-backup/dt-bckp-ip $1

