#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`
DT_LOCATION=$WRDIR
. $WRDIR/init_params

docker run  \
-v $DT_LOCATION/etc/dt-auto-backup.conf:/dt-auto-backup/etc/dt-auto-backup.conf \
-v $BACKUPDIR:/dt-auto-backup/backup \
-v $DT_LOCATION/run:/dt-auto-backup/run \
-v $DT_LOCATION/log:/dt-auto-backup/log \
-v $DT_LOCATION/reports:/dt-auto-backup/reports \
$PRM_SGN \
--net=host \
--rm \
$DOCK_IMAGE /dt-auto-backup/get_loc_net

