#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`


cd $WRDIR

CONFFILE=etc/dt-auto-backup.conf
mkdir -p etc

if  [ ! -f  $CONFFILE ];  then
echo USER= >$CONFFILE
echo PASS= >>$CONFFILE
echo DOMAIN= >>$CONFFILE
echo BASE=dt-auto-backup>>$CONFFILE
echo DOCK_IMAGE=dtcentos/smbenv:solid>>$CONFFILE
echo BACKUPDIR=>>$CONFFILE
echo DELAY=1>>$CONFFILE
echo >>$CONFFILE
fi 

. $WRDIR/init_params

docker  pull $DOCK_IMAGE

test -e /etc/cron.hourly/$BASE'_'start_dt_auto&&rm -f /etc/cron.hourly/$BASE'_'start_dt_auto
test -e /etc/cron.hourly/&&ln -s  $WRDIR/start_dt_auto /etc/cron.hourly/$BASE'_'start_dt_auto

mkdir -p  backup
mkdir -p  reports
mkdir -p  log
mkdir -p  run
chmod +x update_myself
git config --global user.name $HOSTNAME
git config --global user.email dtab@HOSTNAME

cd $SAVEDIR