#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`


cd $WRDIR

CONFFILE=etc/dt-auto-backup.conf
mkdir -p etc

if  [ ! -f  $CONFFILE ];  then
echo USER= >$CONFFILE
echo PASS= >>$CONFFILE
echo DOMAIN= >>$CONFFILE
echo BASE=dt-auto-backup>>$CONFFILE
echo DOCK_IMAGE=dtcentos/smbenv:solid>>$CONFFILE
echo BACKUPDIR=>>$CONFFILE
echo DELAY=1>>$CONFFILE
echo RESET_PERIOD=day>>$CONFFILE
echo >>$CONFFILE
fi 

cp pf-dt etc/pf-dt
cp exc-dt etc/exc-dt


. $WRDIR/init_params

./get_dock_image

rm -f /etc/cron.hourly/$BASE'_'start_dt_auto
test -e /etc/cron.hourly/&&ln -s  $WRDIR/start_dt_auto /etc/cron.hourly/$BASE'_'start_dt_auto


UPDATE_MYSELF=update_myself
rm -f /etc/cron.daily/$BASE'_'$UPDATE_MYSELF
test -e /etc/cron.daily/&&ln -s  $WRDIR/$UPDATE_MYSELF /etc/cron.daily/$BASE'_'$UPDATE_MYSELF


mkdir -p  backup
mkdir -p  reports
mkdir -p  log
mkdir -p  run
chmod +x update_myself
git config --global user.name $HOSTNAME
git config --global user.email dtab@$HOSTNAME

cd $SAVEDIR
