#!/bin/bash


SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`


#docker pull $DOCK_IMAGE

cd $WRDIR

. ./init_params


for CONTAINER in $(docker ps -a    |awk '{print $1}')
do
docker stop   $CONTAINER
docker rm $CONTAINER
done
rm -f run/*.lock
cd $SAVEDIR 