#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`
cd $WRDIR
git config --global user.name $HOSTNAME
git config --global user.email dtab@HOSTNAME


. ./init_params


#git stash
git pull https://github.com/johnlens/dtab.git
chmod +x update_myself
rm -f pf-dt
rm -f exc-dt

./get_dock_image


rm -f /etc/cron.hourly/$BASE'_'start_dt_auto
test -e /etc/cron.hourly/&&ln -s  $WRDIR/start_dt_auto /etc/cron.hourly/$BASE'_'start_dt_auto


UPDATE_MYSELF=update_myself
rm -f /etc/cron.daily/$BASE'_'$UPDATE_MYSELF
test -e /etc/cron.daily/&&ln -s  $WRDIR/$UPDATE_MYSELF /etc/cron.daily/$BASE'_'$UPDATE_MYSELF


cd $SAVEDIR



#endfile
