#!/bin/bash

SAVEDIR=$PWD
AFLNM=`readlink -e "$0"`
WRDIR=`dirname "$AFLNM"`
cd $WRDIR

git stash
git pull https://github.com/johnlens/dtab.git
chmod +x $0
rm -f pf-dt
rm -f exc-dt

cd $SAVEDIR

#endfile